### PR TITLE
Make it run smooth

### PR DESCRIPTION
**Pull request by almarklein**
Performance tweaks to manage how frames are throttled to realize a smooth experience. It turns out Chrome seems to run smooth (more or less) regardless of what we do, but FF needs more care to avoid sending new frames before the old one are actually shown.

* Also rename `push_frame` -> `send_frame`.
* Adds tests for the Python sending code.
* Adds a notebook to test the performance.
* Document the approach.

### CODE REVIEW

**Comment by almarklein** [comment]
I've merged this directly to keep up the pace, but feel free to review @djhoese or @rossant :)

**Comment by rossant** [comment]
Do you have an estimation of the frame rate? do you also have a video demo?

**Comment by almarklein** [comment]
It looks like the frame rate heavily depends on the size of the frame.

So, the widget has a `stats` property that shows some statistics on the performance. The "performance" notebook pushes a series of frames to the browser. Here is the `stat` results when doing this for a 640x480 frame of mostly zeros:
```py
{
 'received_frames': 50,
 'sent_frames': 50,
 'confirmed_frames': 50,
 'dropped_frames': 0,
 'roundtrip': 0.052918088679410974,
 'delivery': 0.03266982642971739,
 'img_encoding': 0.012132593999999698,
 'b64_encoding': 4.410800000009374e-05,
 'fps': 47.02170435343145,
}
```
And frames of the same size, but random data:
```py
{
 'received_frames': 50,
 'sent_frames': 50,
 'confirmed_frames': 50,
 'dropped_frames': 0,
 'roundtrip': 0.3117579174041748,
 'delivery': 0.13540111541748046,
 'img_encoding': 0.08124785999999745,
 'b64_encoding': 0.00524112999999943,
 'fps': 8.781102582021115,
}
```

I haven't dug down much yet, but it looks the image encoding is a major bottleneck. It could be that Pillow can do it faster. And we can look into using jpg, or using decimated frames during interaction, etc.

Anyway, this PR focused on getting the basic implementation right; making sure that the server does not push harder than the client can display the frames. Actual performance improvements are for another time.

----

Screenshot of hello-world example:

image

Animation of performance notebook:

Animation

**Comment by almarklein** [comment]
I'm now working on a vispy backend based on this. That should produce some fancier videos :)

**Comment by rossant** [comment]
Thanks. Looks awesome!

**Pull request merged**
