### PR TITLE
Add release script

### PR DESCRIPTION
**Pull request by almarklein**
Took this from another project. Simple solution to create a new release by running one script, assuming that the build is cross-platform (which this is).

### CODE REVIEW

**Comment by djhoese** [comment]
1. For full support the wheels need to be built for all platforms don't they?
2. Are you planning on adding this to GitHub actions or other CI?
3. Thoughts on using a git tag based version package like setuptools_scm or versioneer?

**Comment by almarklein** [comment]
> For full support the wheels need to be built for all platforms don't they?

No, its a universal wheel, so for this library this approach is fine (a good luxury to have).

> Are you planning on adding this to GitHub actions or other CI?

Not necessarily. It's kinda nice that this just works locally (feels lightweight), and still automates the whole release process, except writing release notes. That said, adding this script does not exclude other approaches :)

> Thoughts on using a git tag based version package like setuptools_scm or versioneer?

Those seem overkill (for a lib like this) to me. Maybe this script was already overkill :)

**Comment by djhoese** [comment]
Does jupyter lab require uploading a javascript library to https://www.npmjs.com/?

**Comment by almarklein** [comment]
> Does jupyter lab require uploading a javascript library to https://www.npmjs.com/?

After talking in meeting: probably not :)

**Comment by almarklein** [comment]
It works, no npm publish needed: https://mybinder.org/v2/gh/vispy/jupyter_rfb/binder?urlpath=lab/tree/examples/hello_world.ipynb

**Pull request merged**
