### PR TITLE
Make things work on other notebook implementations

### LINKED ISSUE #53: Support for VSCode
In VSCode the notebooks are not interactive:

image

image

(Running examples from https://github.com/pygfx/wgpu-py/pull/202)

### PR DESCRIPTION
**Pull request by almarklein**
Closes #53. Might do the same for #57.

I confirmed that this works on VS Code. To this end, I applied two changes:

* [x] The initialization of the widget size is now more reliable. We already needed a timer earlier to set the widget's size after a short delay. In turned out that this was not enough for VS Code. A longer timeout works, but this starts getting iffy and unreliable if e.g. your PR happens to perform an update. Instead the css size values are checked when the size changes.
* [x] I removed the smart initial snapshot trick, because I fear it might be fragile on some implementations. 
* [x] The above made the snapshots disappear from our docs, so I added a bit of doc pre-processing to make that work again.

### CODE REVIEW

**Comment by almarklein** [comment]
RTR @djhoese. The changes to the examples are simply re-rendering with the slightly different snapshot output.

**Comment by kushalkolar** [comment]
Thanks for trying this out! Doesn't work in collab yet unfortunately, same issue with just the snapshot appearing.

I looked into it a bit and it seems like collab uses a CDN for non-standard widgets? I posted an issue there a while ago to try and get more info. https://github.com/googlecolab/colab-cdn-widget-manager 

image

**Comment by almarklein** [comment]
@kushalkolar I think that its still using an earlier version. I can tell because it says "initial snapshot" - the new version's snapshot is simply called "snapshot" :)

**Comment by almarklein** [comment]
I'm going to merge this now and publish a release.

**Pull request merged**
