### PR TITLE
Pre commit hook

### PR DESCRIPTION
**Pull request by almarklein**
As suggested in https://github.com/vispy/jupyter_rfb/pull/5#issuecomment-878355894

### CODE REVIEW

**Comment by almarklein** [comment]
I don't think I'll become a fan myself :)  but it's optional, and I can see how people find it useful.

**Comment by djhoese** [comment]
I realized there are some configs needed to fully control some of these. One sec...

**Comment by djhoese** [comment]
isort: https://github.com/geoxarray/geoxarray/blob/95af8a5aed89e3b3e5cdcc73df36213e1820464c/setup.cfg#L16-L22

flake8: https://github.com/geoxarray/geoxarray/blob/main/.flake8

Both of these can go in setup.cfg I think.

**Comment by djhoese** [comment]
> I don't think I'll become a fan myself :) but it's optional, and I can see how people find it useful.

I'm guessing you'd rather run black manually?

**Comment by almarklein** [comment]
> I'm guessing you'd rather run black manually?

I'm just so used to doing that :P - at least at the stage where a piece of work is ready enough to let CI run fully :)  But maybe I should give it a try ...

**Pull request merged**
