### PR TITLE
Docs via mkdocs

### LINKED ISSUE #9: Documentation

### PR DESCRIPTION
**Pull request by almarklein**
Closes #9 

* [x] Create initial docs with auto generated reference docs.
* [x] Setup RTD.
* [x] Wait for #18 because that affects the docs quite a bit.
* [x] Clean up, complete, and improve the docs.
* [ ] Set RTD branch to `main`. 

See https://jupyter-rfb.readthedocs.io/

### CODE REVIEW

**Comment by djhoese** [comment]
How does mkdocs compare to sphinx for api docs? For example the stuff in the vispy core repository has plugins for auto-generating the api docs from the source when the docs are built. There is also intersphinx which lets us link to other projects. This may be helpful so you can link to jupyter or ipywidgets docs elements. I also have my sphinx-gallery stuff that I just finished up that would be really nice to show produce automatic notebook examples that people can download and run.

**Comment by almarklein** [comment]
My main motivation is that I like markdown so much more than rst :)

mkdocs feels a bit more work to setup (getting RTD configured correctly). But I've done that dance in another project so I had a head-start here.

I use [mkautodoc](https://github.com/tomchristie/mkautodoc) which produces the reference docs. No intersphinx but also there's just one link to ipywidgets. Also there is no actual reference doc for `ipywidgets.Widget` (or I could not find it, if you do, let me know).

Example notebooks is a good point, though we can also leverage Github or MyBinder (?) for that. Not as slick, but this lib is more developer-facing than user-facing, so no need to be too fancy :)

**Comment by djhoese** [comment]
Intersphinx downloads this file:

https://ipywidgets.readthedocs.io/en/latest/objects.inv

Running with the intersphinx module on the command line gives you a lot of output but looks like mostly examples. Looks like they don't document their API:

```
$ python -m sphinx.ext.intersphinx https://ipywidgets.readthedocs.io/en/latest/objects.inv
std:doc
        changelog                                ipywidgets Changelog                    : changelog.html
        contributing                             Contributing                            : contributing.html
        dev_docs                                 Develop and Build Documentation         : dev_docs.html
        dev_install                              Developer Install                       : dev_install.html
        dev_release                              Developer Release Procedure             : dev_release.html
        dev_testing                              Unit Tests                              : dev_testing.html
        developer_docs                           ipywidgets Development                  : developer_docs.html
        embedding                                Embedding Jupyter Widgets in Other Contexts than the Notebook: embedding.html
        examples/Layout Example                  Example.html Weather map                : examples/Layout
        examples/Layout Templates                Templates.html Using Layout Templates   : examples/Layout
        examples/Output Widget                   Widget.html Output widgets: leveraging Jupyter’s display system: examples/Output
        examples/Using Interact                  Interact.html Using Interact            : examples/Using
        examples/Widget Asynchronous             Asynchronous.html Asynchronous Widgets  : examples/Widget
        examples/Widget Basics                   Basics.html Simple Widget Introduction  : examples/Widget
        examples/Widget Custom                   Custom.html Building a Custom Widget - Email widget: examples/Widget
        examples/Widget Events                   Events.html Widget Events               : examples/Widget
        examples/Widget List                     List.html Widget List                   : examples/Widget
        examples/Widget Low Level                Low Level.html Low Level Widget Tutorial: examples/Widget
        examples/Widget Styling                  Styling.html Layout and Styling of Jupyter widgets: examples/Widget
        examples/Widget TagsInput                TagsInput.html TagsInput widget         : examples/Widget
        index                                    ipywidgets                              : index.html
        migration_guides                         Migrating custom widget libraries       : migration_guides.html
        user_install                             Installation                            : user_install.html
std:label
        /changelog.md                            ipywidgets Changelog                    : changelog.html
        ...
```

> Not as slick, but this lib is more developer-facing than user-facing, so no need to be too fancy :)

I personally like consistency, but I also only know sphinx really and I don't care that much here. Go for it.

**Comment by almarklein** [comment]
> I personally like consistency

Yeah I understand that too :)  - I think I might turn this to rst after all.

**Pull request closed without merging**
